# Generated by Django 3.2.16 on 2023-03-15 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0002_building_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone_number', models.CharField(max_length=15)),
                ('floor', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building', to='building.building')),
            ],
        ),
    ]
