# Generated by Django 3.2.16 on 2023-03-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='floor',
            new_name='building_floor',
        ),
    ]
